### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by scally1017** [trubadur-app/trubadur#5]
It would be nice to have an option to change the way in which I scroll through a song. Currently I have to keep the right arrow key pressed to get to the next part of the song. Granted I could change the display settings to fit the whole song, but what If I'm playing 'We Didn’t Start the Fire' by Billy Joel? It would be great to be able to press the arrow key once, and it would show the next column of text.

**Comment by trubadur-app** [comment]
Thanks for pointing this out.

What operating system are you running? On my Macbook I can scroll horizontally with my touchpad and/or mouse. Is this posbile on your computer?

I will also add the key-press scroll that you suggest.

**Comment by trubadur-app** [comment]
This is now fixed in version 1.0.13.

**Comment by trubadur-app** [comment]
**Note:** I didn't change how the arrow works, since the arrows work fine in some operating system and we don't want to mess with that. However, I added the possibility of pressing the space key when displaying a song. The space key will scroll your song a fixed distance.
