### ISSUE TITLE
Trouble registering chords when separated by ' | '

### ISSUE THREAD

**Issue by scally1017** [trubadur-app/trubadur#7]
In many songs, the intro section or solo section will just show the chords, broken up like this: 

|A    |D    |A    |D    |

These lines are often important as they indicate how long the chord should be played for.
There seems to be an issue with recognizing these as chords.

**Comment by trubadur-app** [comment]
Thanks for pointing it out, will fix it!

**Comment by trubadur-app** [comment]
This is now fixed in version 1.0.13.
